"""Markdown report generation."""

from __future__ import annotations

from document_core.schemas.compliance import ComplianceFinding, ReviewReport


def render_markdown_report(report: ReviewReport) -> str:
    lines = [
        f"# Compliance Review — {report.contract_title}",
        "",
        f"**Tenant:** {report.tenant_id}  ",
        f"**Contract document:** `{report.contract_document_id}`  ",
        f"**Structure confidence:** {report.structure_confidence}",
        "",
    ]

    if report.warnings:
        lines.append("## Warnings")
        for warning in report.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    lines.append("## Findings")
    if not report.findings:
        lines.append("_No findings produced._")
    else:
        for finding in report.findings:
            lines.extend(_finding_block(finding))

    lines.append("")
    lines.append("---")
    lines.append("_Generated by review-agent (text MVP). Quotes verified where marked grounded._")
    return "\n".join(lines)


def _finding_block(finding: ComplianceFinding) -> list[str]:
    grounded = "yes" if finding.grounded else "no"
    policy_title = (finding.metadata.get("policy_title") or "").strip()
    lines = [
        f"### {finding.dimension_label} — `{finding.status.value}`",
        f"- **Severity:** {finding.severity.value}",
        f"- **Grounded:** {grounded}",
    ]
    if policy_title:
        lines.append(f"- **Playbook:** {policy_title}")
    if finding.policy_document_id:
        lines.append(f"- **Policy document:** `{finding.policy_document_id}`")
    if finding.status.value == "NON_COMPLIANT" and policy_title:
        lines.append(f"- **Violated policy:** {policy_title} — {finding.dimension_label}")
    lines.extend(
        [
            f"- **Rationale:** {finding.rationale}",
            f"- **Contract quote:** {finding.contract_quote or '—'}",
            f"- **Policy quote:** {finding.policy_quote or '—'}",
            "",
        ]
    )
    return lines
