"""Markdown report generation."""

from __future__ import annotations

from document_core.schemas.compliance import ComplianceFinding, ComplianceStatus, ReviewReport
from review_agent.schemas.review_artifact import ReviewArtifact


def render_markdown_report(
    report: ReviewReport,
    *,
    artifact: ReviewArtifact | None = None,
    llm_summary_paragraph: str = "",
) -> str:
    lines = [
        f"# Compliance Review — {report.contract_title}",
        "",
        f"**Tenant:** {report.tenant_id}  ",
        f"**Contract document:** `{report.contract_document_id}`  ",
        f"**Structure confidence:** {report.structure_confidence}",
        "",
    ]

    summary_lines = _render_executive_summary(report, artifact)
    if summary_lines:
        lines.extend(summary_lines)
        if llm_summary_paragraph:
            lines.append("")
            lines.append(llm_summary_paragraph)
        lines.append("")

    if report.warnings:
        lines.append("## Warnings")
        for warning in report.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    lines.append("## Findings")
    if not report.findings:
        lines.append("_No findings produced._")
    else:
        for finding in report.findings:
            lines.extend(_finding_block(finding))

    if artifact is not None:
        lines.append("")
        lines.extend(_render_ops_block(artifact))

    lines.append("")
    lines.append("---")
    lines.append("_Generated by review-agent (text MVP). Quotes verified where marked grounded._")
    return "\n".join(lines)


def _render_executive_summary(
    report: ReviewReport,
    artifact: ReviewArtifact | None,
) -> list[str]:
    ops = artifact.ops if artifact else None
    reviewable_count = 0
    discovery_count = 0
    if artifact:
        reviewable_count = len(artifact.sections)
        discovery_count = len(artifact.discovery.get("discovered_policy_document_ids") or [])
    elif report.metadata:
        reviewable_count = int(report.metadata.get("reviewable_section_count") or 0)
        discovery_count = len(report.metadata.get("discovered_policy_document_ids") or [])

    non_compliant = sum(
        1 for f in report.findings if f.status == ComplianceStatus.NON_COMPLIANT
    )
    critical = sum(1 for f in report.findings if f.severity.value == "critical")
    policy_conflict = ops.policy_conflict_count if ops else sum(
        1 for f in report.findings if f.status == ComplianceStatus.POLICY_CONFLICT
    )
    retrieval_retry = ops.retrieval_retry_sections if ops else 0
    backfill = ops.backfill_count if ops else int(
        (report.metadata.get("section_coverage") or {}).get("backfill_count") or 0
    )
    ungrounded = ops.ungrounded_count if ops else sum(
        1 for f in report.findings if f.grounded is False
    )
    guard_failed = ops.guard_failed if ops else 0
    guard_inference = ops.guard_inference_ok if ops else 0
    quote_repaired = ops.quote_repair_success if ops else 0
    downgrade_validate = 0
    if artifact and artifact.compliance_stats:
        rc = artifact.compliance_stats.get("review_confidence") or {}
        downgrade_validate = int(rc.get("downgrade_quote_validate") or 0)

    return [
        "## Executive summary",
        "",
        f"Reviewed **{reviewable_count}** contract sections against **{discovery_count}** discovered policies. "
        f"**{non_compliant}** non-compliant, **{critical}** critical, **{policy_conflict}** policy conflicts.",
        f"Retrieval retried **{retrieval_retry}** section(s); **{backfill}** coverage backfill(s). "
        f"**{downgrade_validate}** finding(s) downgraded at compare quote validate; "
        f"**{ungrounded}** failed MCP quote grounding; **{guard_failed}** failed rationale guard; "
        f"**{guard_inference}** inference-only (OK); **{quote_repaired}** quote(s) repaired.",
    ]


def _render_ops_block(artifact: ReviewArtifact) -> list[str]:
    ops = artifact.ops
    return [
        "## Pipeline operations",
        "",
        "| Metric | Value |",
        "|--------|------:|",
        f"| Retrieval retries (sections) | {ops.retrieval_retry_sections} |",
        f"| Max retrieval attempts used | {ops.retrieval_max_attempts_used} |",
        f"| Zero-hit sections | {ops.retrieval_zero_hit_sections} |",
        f"| Degraded sections | {ops.degraded_section_count} |",
        f"| Zero-hit section IDs | {', '.join(ops.retrieval_zero_hit_section_ids) or '—'} |",
        f"| Compare LLM batches failed | {ops.llm_batches_failed} |",
        f"| Gap LLM sections | {ops.gap_llm_sections} |",
        f"| Superseded findings | {ops.superseded_count} |",
        f"| Ungrounded findings | {ops.ungrounded_count} |",
        f"| Grounding downgrades | {ops.grounding_downgraded_count} |",
        f"| Coverage backfill | {ops.backfill_count} |",
        f"| Post-grounding backfill | {ops.post_grounding_backfill_count} |",
        f"| Playbook compare findings | {ops.playbook_compare_count} |",
        f"| Policy conflicts | {ops.policy_conflict_count} |",
        f"| Rationale guard checked | {ops.guard_checked} |",
        f"| Rationale guard failed | {ops.guard_failed} |",
        f"| Quote repair attempts | {ops.quote_repair_attempts} |",
        f"| Quote repair success | {ops.quote_repair_success} |",
        f"| Guard inference OK | {ops.guard_inference_ok} |",
        f"| Guard rationale repair attempts | {ops.guard_repair_attempts} |",
        f"| Guard rationale repair success | {ops.guard_repair_success} |",
    ]


def _finding_block(finding: ComplianceFinding) -> list[str]:
    grounded = "yes" if finding.grounded else "no"
    policy_title = (finding.metadata.get("policy_title") or "").strip()
    lines = [
        f"### {finding.dimension_label} — `{finding.status.value}`",
        f"- **Severity:** {finding.severity.value}",
        f"- **Grounded:** {grounded}",
    ]
    if policy_title:
        lines.append(f"- **Playbook:** {policy_title}")
    if finding.policy_document_id:
        lines.append(f"- **Policy document:** `{finding.policy_document_id}`")
    if finding.status.value == "NON_COMPLIANT" and policy_title:
        lines.append(f"- **Violated policy:** {policy_title} — {finding.dimension_label}")
    lines.append(f"- **Rationale:** {finding.rationale}")
    if finding.status == ComplianceStatus.NON_COMPLIANT:
        lines.append("- **Contract text (violates policy):**")
        lines.append(f"  > {finding.contract_quote or '—'}")
        lines.append("- **Policy text (required standard):**")
        lines.append(f"  > {finding.policy_quote or '—'}")
    else:
        lines.extend(
            [
                f"- **Contract quote:** {finding.contract_quote or '—'}",
                f"- **Policy quote:** {finding.policy_quote or '—'}",
            ]
        )
    lines.append("")
    return lines
